version: "3.9"
networks: 
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
services:
  snort:
    container_name: snort
    build: snort
    ports: 
      - 8007:80
    networks:
      test:
        ipv4_address: 10.1.0.100
    restart: on-failure
