version: "3.9"
networks: 
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
services:
  snort:
    container_name: snort
    build: snort
    ports: 
      - 8007:80
    networks:
      test:
        ipv4_address: 10.1.0.100
    restart: on-failure
  nmap:
    container_name: nmap
    build: nmap
    ports:
      - 8009:80
      - 8008:443
    networks:
      test:
        ipv4_address: 10.1.0.101
    restart: on-failure
  splunk:
    image: splunk/splunk:latest
    # username is admin
    environment: 
    - "SPLUNK_START_ARGS= --accept-license" 
    - "SPLUNK_PASSWORD=thesis2021"
    ports:
      - 8010:80
      - 8011:443
      - 8012:8000
    networks:
      test:
        ipv4_address: 10.1.0.102
    restart: on-failure
